<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class FillTarifaRecoleccionBasura2024 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $now = now();
        DB::table('tarifa_recoleccion_basura2024')->
            insert([
                //  SECTOR COMERCIO, VOLUMEN BAJO
                [
                    'descripcion' => 'Sector Comercio, Volumen Bajo, Tipo tarifa Autoempleo',
                    'volumen' => 'BAJO',
                    'sector' => 'COMERCIO',
                    'tipo_tarifa' => 'AUTOEMPLEO',
                    'valor' => (4 / 12),
                    'valor_anual' => 4,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Comercio, Volumen Bajo, Tipo tarifa Micro',
                    'volumen' => 'BAJO',
                    'sector' => 'COMERCIO',
                    'tipo_tarifa' => 'MICRO',
                    'valor' => (9 / 12),
                    'valor_anual' => 9,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Comercio, Volumen Bajo, Tipo tarifa Pequeña',
                    'volumen' => 'BAJO',
                    'sector' => 'COMERCIO',
                    'tipo_tarifa' => 'PEQUEÑA',
                    'valor' => (37 / 12),
                    'valor_anual' => 37,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Comercio, Volumen Bajo, Tipo tarifa Autoempleo',
                    'volumen' => 'BAJO',
                    'sector' => 'COMERCIO',
                    'tipo_tarifa' => 'MEDIANA',
                    'valor' => (144 / 12),
                    'valor_anual' => 144,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Comercio, Volumen Bajo, Tipo tarifa Grande',
                    'volumen' => 'BAJO',
                    'sector' => 'COMERCIO',
                    'tipo_tarifa' => 'GRANDE',
                    'valor' => (280 / 12),
                    'valor_anual' => 280,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                //  SECTOR COMERCIO, VOLUMEN MEDIO
                [
                    'descripcion' => 'Sector Comercio, Volumen Medio, Tipo tarifa Autoempleo',
                    'volumen' => 'MEDIO',
                    'sector' => 'COMERCIO',
                    'tipo_tarifa' => 'AUTOEMPLEO',
                    'valor' => (9 / 12),
                    'valor_anual' => 9,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Comercio, Volumen Medio, Tipo tarifa Micro',
                    'volumen' => 'MEDIO',
                    'sector' => 'COMERCIO',
                    'tipo_tarifa' => 'MICRO',
                    'valor' => (18 / 12),
                    'valor_anual' => 18,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Comercio, Volumen Medio, Tipo tarifa Pequeña',
                    'volumen' => 'MEDIO',
                    'sector' => 'COMERCIO',
                    'tipo_tarifa' => 'PEQUEÑA',
                    'valor' => (45 / 12),
                    'valor_anual' => 45,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Comercio, Volumen Medio, Tipo tarifa Mediana',
                    'volumen' => 'MEDIO',
                    'sector' => 'COMERCIO',
                    'tipo_tarifa' => 'MEDIANA',
                    'valor' => (290 / 12),
                    'valor_anual' => 290,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Comercio, Volumen Medio, Tipo tarifa Grande',
                    'volumen' => 'MEDIO',
                    'sector' => 'COMERCIO',
                    'tipo_tarifa' => 'GRANDE',
                    'valor' => (515 / 12),
                    'valor_anual' => 515,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                //  SECTOR COMERCIO, VOLUMEN ALTO
                [
                    'descripcion' => 'Sector Comercio, Volumen Medio, Tipo tarifa Autoempleo',
                    'volumen' => 'ALTO',
                    'sector' => 'COMERCIO',
                    'tipo_tarifa' => 'AUTOEMPLEO',
                    'valor' => (13 / 12),
                    'valor_anual' => 13,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Comercio, Volumen Alto, Tipo tarifa Micro',
                    'volumen' => 'ALTO',
                    'sector' => 'COMERCIO',
                    'tipo_tarifa' => 'MICRO',
                    'valor' => (26 / 12),
                    'valor_anual' => 26,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Comercio, Volumen Alto, Tipo tarifa Pequeña',
                    'volumen' => 'ALTO',
                    'sector' => 'COMERCIO',
                    'tipo_tarifa' => 'PEQUEÑA',
                    'valor' => (56 / 12),
                    'valor_anual' => 56,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Comercio, Volumen Alto, Tipo tarifa Mediana',
                    'volumen' => 'ALTO',
                    'sector' => 'COMERCIO',
                    'tipo_tarifa' => 'MEDIANA',
                    'valor' => (440 / 12),
                    'valor_anual' => 440,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Comercio, Volumen Alto, Tipo tarifa Grande',
                    'volumen' => 'ALTO',
                    'sector' => 'COMERCIO',
                    'tipo_tarifa' => 'GRANDE',
                    'valor' => (800 / 12),
                    'valor_anual' => 800,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                //  SECTOR SERVICIOS, VOLUMEN BAJO
                [
                    'descripcion' => 'Sector Servicios, Volumen Bajo, Tipo tarifa Autoempleo',
                    'volumen' => 'BAJO',
                    'sector' => 'SERVICIOS',
                    'tipo_tarifa' => 'AUTOEMPLEO',
                    'valor' => (4 / 12),
                    'valor_anual' => 4,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Servicios, Volumen Bajo, Tipo tarifa Micro',
                    'volumen' => 'BAJO',
                    'sector' => 'SERVICIOS',
                    'tipo_tarifa' => 'MICRO',
                    'valor' => (13 / 12),
                    'valor_anual' => 13,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Servicios, Volumen Bajo, Tipo tarifa Pequeña',
                    'volumen' => 'BAJO',
                    'sector' => 'SERVICIOS',
                    'tipo_tarifa' => 'PEQUEÑA',
                    'valor' => (54 / 12),
                    'valor_anual' => 54,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Servicios, Volumen Bajo, Tipo tarifa Mediana',
                    'volumen' => 'BAJO',
                    'sector' => 'SERVICIOS',
                    'tipo_tarifa' => 'MEDIANA',
                    'valor' => (165 / 12),
                    'valor_anual' => 165,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Servicios, Volumen Bajo, Tipo tarifa Grande',
                    'volumen' => 'BAJO',
                    'sector' => 'SERVICIOS',
                    'tipo_tarifa' => 'GRANDE',
                    'valor' => (290 / 12),
                    'valor_anual' => 290,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                //  SECTOR SERVICIOS, VOLUMEN MEDIO
                [
                    'descripcion' => 'Sector Servicios, Volumen Medio, Tipo tarifa Autoempleo',
                    'volumen' => 'MEDIO',
                    'sector' => 'SERVICIOS',
                    'tipo_tarifa' => 'AUTOEMPLEO',
                    'valor' => (9 / 12),
                    'valor_anual' => 9,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Servicios, Volumen Medio, Tipo tarifa Micro',
                    'volumen' => 'MEDIO',
                    'sector' => 'SERVICIOS',
                    'tipo_tarifa' => 'MICRO',
                    'valor' => (25 / 12),
                    'valor_anual' => 25,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Servicios, Volumen Medio, Tipo tarifa Pequeña',
                    'volumen' => 'MEDIO',
                    'sector' => 'SERVICIOS',
                    'tipo_tarifa' => 'PEQUEÑA',
                    'valor' => (108 / 12),
                    'valor_anual' => 108,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Servicios, Volumen Medio, Tipo tarifa Mediana',
                    'volumen' => 'MEDIO',
                    'sector' => 'SERVICIOS',
                    'tipo_tarifa' => 'MEDIANA',
                    'valor' => (305 / 12),
                    'valor_anual' => 305,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Servicios, Volumen Medio, Tipo tarifa Grande',
                    'volumen' => 'MEDIO',
                    'sector' => 'SERVICIOS',
                    'tipo_tarifa' => 'GRANDE',
                    'valor' => (540 / 12),
                    'valor_anual' => 540,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                //  SECTOR SERVICIOS, VOLUMEN ALTO
                [
                    'descripcion' => 'Sector Servicios, Volumen Alto, Tipo tarifa Autoempleo',
                    'volumen' => 'ALTO',
                    'sector' => 'SERVICIOS',
                    'tipo_tarifa' => 'AUTOEMPLEO',
                    'valor' => (13 / 12),
                    'valor_anual' => 13,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Servicios, Volumen Alto, Tipo tarifa Micro',
                    'volumen' => 'ALTO',
                    'sector' => 'SERVICIOS',
                    'tipo_tarifa' => 'MICRO',
                    'valor' => (51 / 12),
                    'valor_anual' => 51,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Servicios, Volumen Alto, Tipo tarifa Pequeña',
                    'volumen' => 'ALTO',
                    'sector' => 'SERVICIOS',
                    'tipo_tarifa' => 'PEQUEÑA',
                    'valor' => (217 / 12),
                    'valor_anual' => 217,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Servicios, Volumen Alto, Tipo tarifa Mediana',
                    'volumen' => 'ALTO',
                    'sector' => 'SERVICIOS',
                    'tipo_tarifa' => 'MEDIANA',
                    'valor' => (460 / 12),
                    'valor_anual' => 460,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Servicios, Volumen Alto, Tipo tarifa Grande',
                    'volumen' => 'ALTO',
                    'sector' => 'SERVICIOS',
                    'tipo_tarifa' => 'GRANDE',
                    'valor' => (810 / 12),
                    'valor_anual' => 810,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                //  SECTOR INDUSTRIA, VOLUMEN BAJO
                [
                    'descripcion' => 'Sector Industria, Volumen Bajo, Tipo tarifa Autoempleo',
                    'volumen' => 'BAJO',
                    'sector' => 'INDUSTRIA',
                    'tipo_tarifa' => 'AUTOEMPLEO',
                    'valor' => (13 / 12),
                    'valor_anual' => 13,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Industria, Volumen Bajo, Tipo tarifa Micro',
                    'volumen' => 'BAJO',
                    'sector' => 'INDUSTRIA',
                    'tipo_tarifa' => 'MICRO',
                    'valor' => (27 / 12),
                    'valor_anual' => 27,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Industria, Volumen Bajo, Tipo tarifa Pequeña',
                    'volumen' => 'BAJO',
                    'sector' => 'INDUSTRIA',
                    'tipo_tarifa' => 'PEQUEÑA',
                    'valor' => (435 / 12),
                    'valor_anual' => 435,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Industria, Volumen Bajo, Tipo tarifa Mediana',
                    'volumen' => 'BAJO',
                    'sector' => 'INDUSTRIA',
                    'tipo_tarifa' => 'MEDIANA',
                    'valor' => (600 / 12),
                    'valor_anual' => 600,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Industria, Volumen Bajo, Tipo tarifa Grande',
                    'volumen' => 'BAJO',
                    'sector' => 'INDUSTRIA',
                    'tipo_tarifa' => 'GRANDE',
                    'valor' => (750 / 12),
                    'valor_anual' => 750,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                //  SECTOR INDUSTRIA, VOLUMEN MEDIO
                [
                    'descripcion' => 'Sector Industria, Volumen Medio, Tipo tarifa Autoempleo',
                    'volumen' => 'MEDIO',
                    'sector' => 'INDUSTRIA',
                    'tipo_tarifa' => 'AUTOEMPLEO',
                    'valor' => (18 / 12),
                    'valor_anual' => 18,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Industria, Volumen Medio, Tipo tarifa Micro',
                    'volumen' => 'MEDIO',
                    'sector' => 'INDUSTRIA',
                    'tipo_tarifa' => 'MICRO',
                    'valor' => (36 / 12),
                    'valor_anual' => 36,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Industria, Volumen Medio, Tipo tarifa Pequeña',
                    'volumen' => 'MEDIO',
                    'sector' => 'INDUSTRIA',
                    'tipo_tarifa' => 'PEQUEÑA',
                    'valor' => (495 / 12),
                    'valor_anual' => 495,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Industria, Volumen Medio, Tipo tarifa Mediana',
                    'volumen' => 'MEDIO',
                    'sector' => 'INDUSTRIA',
                    'tipo_tarifa' => 'MEDIANA',
                    'valor' => (650 / 12),
                    'valor_anual' => 650,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Industria, Volumen Medio, Tipo tarifa Grande',
                    'volumen' => 'MEDIO',
                    'sector' => 'INDUSTRIA',
                    'tipo_tarifa' => 'GRANDE',
                    'valor' => (810 / 12),
                    'valor_anual' => 810,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                //  SECTOR INDUSTRIA, VOLUMEN ALTO
                [
                    'descripcion' => 'Sector Industria, Volumen Alto, Tipo tarifa Autoempleo',
                    'volumen' => 'ALTO',
                    'sector' => 'INDUSTRIA',
                    'tipo_tarifa' => 'AUTOEMPLEO',
                    'valor' => (22 / 12),
                    'valor_anual' => 22,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Industria, Volumen Alto, Tipo tarifa Micro',
                    'volumen' => 'ALTO',
                    'sector' => 'INDUSTRIA',
                    'tipo_tarifa' => 'MICRO',
                    'valor' => (46 / 12),
                    'valor_anual' => 46,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Industria, Volumen Alto, Tipo tarifa Pequeña',
                    'volumen' => 'ALTO',
                    'sector' => 'INDUSTRIA',
                    'tipo_tarifa' => 'PEQUEÑA',
                    'valor' => (535 / 12),
                    'valor_anual' => 535,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Industria, Volumen Alto, Tipo tarifa Mediana',
                    'volumen' => 'ALTO',
                    'sector' => 'INDUSTRIA',
                    'tipo_tarifa' => 'MEDIANA',
                    'valor' => (710 / 12),
                    'valor_anual' => 710,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'descripcion' => 'Sector Industria, Volumen Alto, Tipo tarifa Grande',
                    'volumen' => 'ALTO',
                    'sector' => 'INDUSTRIA',
                    'tipo_tarifa' => 'GRANDE',
                    'valor' => (870 / 12),
                    'valor_anual' => 870,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                // Servicio de recolección de basura a semifijos que laboren en la vía pública.
                [
                    'descripcion' => 'Servicio de recolección de basura a semifijos que laboren en la vía pública.',
                    'volumen' => null,
                    'sector' => null,
                    'tipo_tarifa' => null,
                    'valor' => 0.66,
                    'valor_anual' => 7.92,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                // Servicio de recolección de basura a locatarios de mercados municipales en el Municipio de La Paz.
                [
                    'descripcion' => 'Servicio de recolección de basura a locatarios de mercados municipales en el Municipio de La Paz.',
                    'volumen' => null,
                    'sector' => null,
                    'tipo_tarifa' => null,
                    'valor' => 1.25,
                    'valor_anual' => 15,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
            ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
